const replySentences = [
  "That’s a pretty face if I’ve ever seen one!!! 😍👀❤️✨",
  "Wow youre HOT!!! 🥵🔥❤️‍🔥",
  "Oh my goodness, absolute PERFECTION right here!!! 🥹💖👑",
  "Seriously, how is it even possible to look THIS stunning?!?? 🥰💞",
  "Wow wow WOW, you are literally glowing!!! 🌟❤️‍🔥✨",
  "A literal angel walking among us!!! 😇💞😭❤️",
  "Excuse me?! This heat should be illegal!!! 🚨🔥😮‍💨",
  "Absolutely smoking hot!!! 🥵🌶️💥🔥",
  "Jaw = dropped 🤤❤️‍🔥💥",
  "You are completely UNREAL!!! 😱💖👑",
  "Someone call the fire department ASAP!!! 🧯🔥🥵",
  "You are blinding me with that beauty!!! 😎💖✨",
  "Looked up ‘flawless’ in the dictionary and there’s only this picture!!! 📖💘😍",
  "Showstopper energy right here!!! 🎭❤️‍🔥🙌",
  "Simply breathtaking!!! 😮‍💨💞💖",
  "Sending this straight to a museum because it’s a masterpiece!!! 🖼️🎨💕",
  "I am looking RESPECTFULLY but wow, stunning!!! 😍❤️‍🔥👑",
  "Head turned completely around!!! 🔄👀🥊💖",
  "My heart cannot take this level of gorgeousness!!! 💔❤️‍🔥🚑",
  "Simply unmatched!!! 🥇💞💅🔥",
  "YOOOO, what is target zero?! You look total shesek!!! 😱🍊🔥❤️‍🔥",
  "Listen to me and listen good, you are end of the world hot!!! 🌍💥🥵🔥",
  "No, truly, there are no such things like this beauty!!! 😮‍💨🙌💞👑",
  "Abale ve'Imale, what a face!!! 👨‍👩‍👧‍👦😍❤️‍🔥",
  "Imale, what a stunning face if I ever seen one!!! 😱❤️‍🔥👑🔥",
  "SLAYYYY🔥💖❤️‍🔥",
  "Wawaweewa, this face is very nice, I like!!! 💥👍😍❤️‍🔥",
  "King of the castle, king of the castle, WOW!!! 🏰👑👀✨",
  "Kapara! what is this magic??💰💎🤩💞",
  "You look like million shekel noder neder!!! 💰💎🤩💞",
  "Okayyyyy but HOW are you this gorgeous?!?! 😩💖💖",
  "That smile?!?!?!? HELLOOOOO 😭💕✨",
  "I swear this picture just attacked me with beauty 😩💘💘",
  "You really woke up and decided to look AMAZING huh?!?! 😩✨❤️",
  "I’m sorry but this is actually model behavior 😭💘✨",
  "I literally said WOW out loud 😩💘✨",
  "Absolutely SERVINGGGGG 😍🔥❤️‍🔥",
  "Can we talk about how AMAZING you look?!?! 😭💕💕",
  "This pic just raised the temperature in here by 100 degrees!!! 🌡️🔥😍",
  "I cannot handle this level of iconic beauty right now!!! 👑💖⚡",
  "Every single detail is perfection!!! ✅💘✨",
  "This is elite-level gorgeousness!!! 🚀💞😮‍💨",
  "Main character energy turned all the way up!!! 🎬🔥💫",
  "You snapped so hard with this one!!! 📸💥❤️",
  "Truly next dimension!!! 🚀💞😮‍💨",
  "Meccha Kireiida!!! (Super Beautiful in Japanese) 😍🇯🇵✨",
  "Sonna utsukushii kao!!! (Such a Beautiful Face in Japanese) 😍🇯🇵✨",
];

module.exports = () => {
  const randomIndex = Math.floor(Math.random() * replySentences.length);
  return replySentences[randomIndex];
};
